---
title: "Introduction to the funres package"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{intro}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = TRUE,
  cache = TRUE,
  fig.width = 6,
  fig.asp = 0.618,
  out.width = "70%"
)
```

**WARNING**: This vignette is very much a work in progress and is subject to change as the package evolves!

```{r setup}
library(VGAM)
library(funres)
library(ggplot2)

theme_set(theme_bw())
```

First, let's simulate some ordinal data:
```{r data}
set.seed(3)
x1 <- rnorm(1000, mean = 0, sd = 1)
x2 <- x1 ^ 2
eta1 <- 1.5*x1 - x2
eta2 <- 1.5 + 1.5*x1 - x2
eta3 <- -1 + 1.5*x1 - x2
eta4 <- 1 + 1.5*x1 - x2
p1 <- 1/(1+exp(-eta1)+exp(-(eta1+eta2))+exp(-(eta1+eta2+eta3))+exp(-(eta1+eta2+eta3+eta4)))
p2 <- exp(-eta1)/(1+exp(-eta1)+exp(-(eta1+eta2))+exp(-(eta1+eta2+eta3))+exp(-(eta1+eta2+eta3+eta4)))
p3 <- exp(-(eta1+eta2))/(1+exp(-eta1)+exp(-(eta1+eta2))+exp(-(eta1+eta2+eta3))+exp(-(eta1+eta2+eta3+eta4)))
p4 <- exp(-(eta1+eta2+eta3))/(1+exp(-eta1)+exp(-(eta1+eta2))+exp(-(eta1+eta2+eta3))+exp(-(eta1+eta2+eta3+eta4)))
p5 <- exp(-(eta1+eta2+eta3+eta4))/(1+exp(-eta1)+exp(-(eta1+eta2))+exp(-(eta1+eta2+eta3))+exp(-(eta1+eta2+eta3+eta4)))
pr <- cbind(p1, p2, p3, p4, p5)
y <- c()
for (i in 1:length(x1)) {
  y[i] <- sample(c(1, 2, 3, 4, 5), size = 1, replace = TRUE, prob = pr[i,]) 
}
df <- data.frame(x1, x2, y)
```

Next, we'll fit an adjacent categories regression model:
```{r acat}
fit <- vglm(y ~ x1 + x2, data = df, family = acat(reverse = TRUE, parallel = TRUE))
summary(fit)
```

Finally, we'll compute the functional residuals and construct a functional residual-vs-predictor plot.
```{r fres}
fr <- fresiduals(fit)
head(fr)
class(fr)
frplot(fr, x = df$x1)
```
